# Docs for Azure Web Apps Deploy: https://github.com/Azure/webapps-deploy
name: Build and deploy Node.js app to Azure Web App - exp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3️⃣ Install dependencies and build
      - name: Install dependencies & Build
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present

      # 4️⃣ Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      # 1️⃣ Download artifact from build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # 2️⃣ Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # 3️⃣ Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'exp'
          slot-name: 'Production'
          package: ./node-app
