name: Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main  # أو الفرع اللي تستخدمه

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend  # ← عدلها حسب مجلدك

      - name: Build app (اختياري)
        run: npm run build
        working-directory: ./backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: your-app-name-here  # ← استبدله باسم Web App من Azure
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./backend
