name: Deploy Node.js App to Azure Web App

on:
  push:
    branches:
      - main  # ← غيّرها إذا تشتغل على فرع مختلف

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend  # ← غيّرها إذا مجلد الكود مو اسمه backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: wallet3-a8d7h3hvhmdpdke4  # ← اسم التطبيق من Azure بالضبط
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./backend  # ← تأكد أن المسار صحيح
